// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 * NaviShooterCore 플러그인에서 사용하는 네이티브 게임플레이 태그들을 정의합니다.
 * 싱글톤 Manager 구조 대신, 정적 태그 선언을 모아두는 네임스페이스 방식을 사용합니다.
 */
namespace NaviShooterCoreGameplayTags
{
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_FireRate);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_RunSpeed);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_EquipSpeed);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_ReloadSpeed);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_MagazineSize);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_MaxAmmo);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_FirstShotSpread);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_FirstShotSpread_HipFire);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_FirstShotSpread_ADS);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_CreditCost);
	
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_Damage_Head);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_Damage_Body);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_Damage_Leg);
	NAVISHOOTERCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Stat_Damage_Falloffs);

	// 필요시 추가 태그 정의
}
