// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace LyraGameplayTags
{
	LYRAGAME_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that Lyra will use
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Team_Changed);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	LYRAGAME_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	LYRAGAME_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Duelist);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Initiator);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Sentinel);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Controller);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_Passive);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_Passive_1);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_Passive_2);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_C);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_Q);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_E);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_X);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Duelist_Phoenix);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Duelist_Yoru);
	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Initiator_KayO);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Initiator_Sova);

	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Sentinel_Sage);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Sentinel_Cypher);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Controller_Viper);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Controller_Brimstone);
	
};
