// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace LyraGameplayTags
{
	LYRAGAME_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that Lyra will use
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Team_Changed);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	LYRAGAME_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	LYRAGAME_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
	
	// Experience (Mod) Tags
	// Already created in Lyra Projcet

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_ShooterGame_Elimination);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_ShooterGame_ControlPoints);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_ShooterGame_Test_Basic);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_ShooterGame_Test_Automated);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_ShooterGame_Test_Perf);
	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_TopDownArena);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_TopDownArena_Multiplayer);
	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_Default);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_FrontEnd);
	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lyra_Experience_TestInventory);


	
};

namespace NaviGameplayTags
{
	// Valorant 관련 Tag
	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Duelist);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Initiator);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Sentinel);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Controller);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_Passive);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_Passive_1);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_Passive_2);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_C);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_Q);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_E);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Skill_X);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Duelist_Phoenix);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Duelist_Yoru);
	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Initiator_KayO);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Initiator_Sova);
	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Sentinel_Sage);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Sentinel_Cypher);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Controller_Viper);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Class_Controller_Brimstone);

	// 무기, 방어 Tag

	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sidearms);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Melee);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Spike);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Armor);
	
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sidearms_Classic);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sidearms_Shorty);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sidearms_Frenzy);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sidearms_Ghost);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sidearms_Sheriff);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sidearms_GoldenGun);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sidearms_SnowballLauncher);

	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_SMGs_Stinger);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_SMGs_Spectre);

	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_Shotguns_Bucky);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_Shotguns_Judge);

	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_Rifles_Bulldog);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_Rifles_Guardian);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_Rifles_Phantom);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_Rifles_Vandal);

	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_SniperRifles_Marshal);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_SniperRifles_Outlaw);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_SniperRifles_Operator);

	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_MachineGuns_Ares);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Primary_MachineGuns_Odin);

	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Melee_Default);

	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Armor_LightArmor);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Armor_RegenShield);
	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Armor_HeavyArmor);
	
	// Agent Change Event Tags
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Selection_Added);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Selection_Removed);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Selection_Changed);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Selection_Confirm);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent_Selection_AllPlayerConfirm);

	// Map Tags
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Map_ShooterGym);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Map_PerformanceTest);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Map_FeatureTest);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Map_Ascent);

	// Navi Project
	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Experience_FrontEnd);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Experience_Lobby);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Experience_AgentSelection);

	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Experience_Normal);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Experience_TeamDeathMatch)


	LYRAGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Kill_Message);
	
	// Creds System Message
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Creds_Award);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Creds_Spend);

	
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Creds_Award_PistolRound);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Creds_Award_Round_Win);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Creds_Award_Round_Defeat);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Creds_Award_Kill);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Experience_PlantSpike);


	// Cheat Tags
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Navi_Cheat_InfiniteCreds);

}